Allow serializing/deserializing waffle models by natural key
django-waffle/django-waffle pull request #285
Opened 2018-03-28 06:36 UTC by bhomnick

We find it useful when building fixtures between environments to use natural keys to avoid collisions with incremental integer PKs. This patch adds support for dumping/loading waffle models by name.

2018-03-28 15:57 UTC, clintonb requested changes
I'm not convinced this is necessary. You can already call `.get(name='some-string')`. Why do you need an alias for that call?

2018-03-29 01:59 UTC, bhomnick commented
@clintonb These are used by the `manage.py dumpdata --natural-primary` and `manage.py loaddata` commands to generate and load fixtures.

2018-03-29 02:28 UTC, clintonb reviewed
Thanks or the explanation. Please add a couple tests to ensure this functionality is not inadvertently modified in the future.

2018-03-30 03:05 UTC, clintonb approved these changes

2018-03-30 03:05 UTC, merged