Improve admin site for users and groups.
django-waffle/django-waffle pull request #316
Opened 2018-12-13 16:21 UTC by PetterS

- Use the regular list widget for groups (there are likely not
  that many, so performance should not be an issue).
- Keep the users as a raw_id field, but display the selected users
  after the input box in a parenthesized list.

Fixes #313.

2018-12-13 16:23 UTC, PetterS commented
Will likely have to do some work to support e.g. Python 2.7 with this patch.

2018-12-17 17:11 UTC, clintonb commented
@PetterS would you post some before/after screenshots, please?

2018-12-19 07:23 UTC, PetterS commented
@clintonb sure, I updated the description.

2018-12-19 15:06 UTC, clintonb requested changes
Good to go once the import is fixed.

2018-12-19 15:06 UTC, clintonb commented on waffle/tests/test_admin.py
> +from unittest import mock
```python
try:
    import mock
except ImportError:
    import unittest.mock as mock
```

2018-12-19 16:13 UTC, PetterS commented on waffle/tests/test_admin.py
> +from unittest import mock
Done.

2018-12-19 16:16 UTC, clintonb approved these changes

2018-12-19 16:18 UTC, PetterS commented
Let me see if I can create a python2 environment and fix the errors.

2018-12-19 16:23 UTC, cleder commented on waffle/admin.py
> +        return super().formfield_for_dbfield(db_field, **kwargs)
`return super(FlagAdmin, self).formfield_for_dbfield(db_field, **kwargs)` for python 2 compatibility

2018-12-19 16:26 UTC, PetterS commented on waffle/admin.py
> +        return super().formfield_for_dbfield(db_field, **kwargs)
Now I ran the tests with both 2.7 and 3.6.

2018-12-19 16:27 UTC, clintonb approved these changes

2018-12-22 09:49 UTC, PetterS commented
Anything left to do here? This should be based on the latest commit to master.

2018-12-22 15:40 UTC, merged

2018-12-22 16:46 UTC, PetterS commented
Thanks a lot @clintonb! Really helpful for us!