Add support for Django 3.1+ and drop Django 1.11, 2.0
django-waffle/django-waffle pull request #378
Opened 2020-08-18 10:42 UTC by hugorodgerbrown

Fixes #376 

---

Django 3.1 introduces a deprecation warning for the `NullBooleanField`, and recommends switching to a `BooleanField` with `null=True` set. This field only supports `null` arguments from 2.1 on (https://docs.djangoproject.com/en/2.1/ref/models/fields/#booleanfield), which means it is not possible to support <2.1 and >3.1 together.

This PR therefore drops 1.11, 2.0 support. The package classifiers have been updated to reflect this.

2020-08-22 19:16 UTC, clintonb requested changes
Thanks for the updates.

2020-08-22 19:16 UTC, clintonb commented on CHANGES
> +v1.1.0
2.0.0. We follow semantic versioning (https://semver.org/). Dropping support for a Django version is a major change.

2020-08-24 08:04 UTC, hugorodgerbrown commented on CHANGES
> +v1.1.0
Do you want me to change the version in `setup.py` - or will you do that when you merge / release?

2020-08-24 08:05 UTC, hugorodgerbrown commented on CHANGES
> +v1.1.0
CHANGELOG has been updated.

2020-08-24 22:13 UTC, clintonb approved these changes

2020-08-24 22:14 UTC, merged

2020-08-31 09:22 UTC, PetterS commented
@clintonb do you think you could make a new release with this PR? Cheers!