Cache auto-created missing flags
django-waffle/django-waffle pull request #379
Opened 2020-08-18 22:20 UTC by simonlindholm

Fixes #343.

2020-08-22 19:09 UTC, clintonb requested changes
Thanks for the changes. I'm happy to merge once the changes are made. Note that I may be a bit slower to respond as I am on parental leave.

2020-08-22 19:09 UTC, clintonb commented on waffle/models.py
> +                new_obj = get_waffle_flag_model().objects.get_or_create(
This is a bit more standard in Python when accessing multiple returned objects than an index selector. Additionally, the variable name is more descriptive.

`flag, _created = get_waffle_flag_model().objects.get_or_create(`

2020-08-22 19:09 UTC, clintonb commented on waffle/models.py
> +                )[0]
Ditch the array selector.

2020-08-22 19:09 UTC, clintonb commented on waffle/models.py
> +                cache.add(self._cache_key(self.name), new_obj)
s/new_obj/flag

2020-08-22 19:09 UTC, clintonb commented on waffle/models.py
> +                new_obj = Switch.objects.get_or_create(
Same as above, but change the variable name to `switch`.

2020-08-22 19:09 UTC, clintonb commented on waffle/models.py
> +                )[0]
Ditch the index selector.

2020-08-22 19:09 UTC, clintonb commented on waffle/models.py
> +                cache.add(self._cache_key(self.name), new_obj)
s/new_obj/switch

2020-08-22 19:09 UTC, clintonb commented on waffle/models.py
> +                new_obj = Sample.objects.get_or_create(
Same as above...

2020-08-22 19:09 UTC, clintonb commented on waffle/tests/test_waffle.py
> +        with self.assertNumQueries(0):
Add a comment above this context, explaining why it's here. I have a suspicion this may come back to bite us in the future. Something like this should be fine...

```
# We assert no queries are made to ensure flags created when the `CREATE_MISSING_FLAGS` setting is active  are properly cached.
```

Do the same for the other test updates, remembering to swap the correct component type (e.g., flag, sample, switch).

2020-09-02 08:09 UTC, simonlindholm commented
I've made the requested changes.

2020-09-02 20:53 UTC, clintonb approved these changes

2020-09-02 20:53 UTC, merged