Add Django 5 and python 3.12 and 3.13 test support
django-waffle/django-waffle pull request #511
Opened 2024-11-06 18:21 UTC by dancergraham

based on https://github.com/jazzband/django-waffle/pull/484/commits

2024-11-07 18:07 UTC, ulgens requested changes
I'm not sure if I'm the right person to give reviews on this package but I think other people will agree that this PR does too much. Python 3.8 removal, Github Actions updates, partial Django 3.2 removal, 4.0 and 4.1 removal, Django 5.1 support and then Python 3.12 and 3.13 support. Almost all of them deserve their own comprehensive PR.

2024-11-08 03:44 UTC, clintonb commented
I agree that there is too much here. Please create separate pull requests for updating Actions and adding support for new Python and Django versions. We can drop support for EOL’d versions in a later, major, release.

2024-11-08 09:56 UTC, dancergraham commented
Hi thanks for the review ! yes I agree that this is mixing subjects, as did the PR I based it on. I will try to find some time to redo it in separate steps...

2024-11-09 07:21 UTC, cclauss commented on tox.ini
> +
```suggestion
	django50: Django>=5.0,<5.1
	django51: Django>=5.1,<5.2
```

2024-11-09 07:22 UTC, cclauss commented on pyproject.toml
> +    "Framework :: Django :: 5.2",
```suggestion
```

2024-11-09 07:22 UTC, cclauss approved these changes
Nice!

2024-11-10 16:02 UTC, closed without merging

2024-11-10 16:03 UTC, dancergraham commented
Handled elsewhere - 9 PRs is better than one ;)