[improvement] Add Django 5.1 support
django-waffle/django-waffle pull request #520
Opened 2024-11-09 17:48 UTC by ulgens

2024-11-09 19:05 UTC, cclauss approved these changes

2024-11-09 20:33 UTC, cclauss requested changes
Please add Python 3.13 to the testing because Django v5.1 adds support for it.

2024-11-09 22:16 UTC, ulgens commented
@cclauss Purpose of these PRs are adding these versions individually. 3.13 will be a separate one.

2024-11-09 22:48 UTC, cclauss commented
Testing Django v5.1 should cover all versions of Python that it supports.

2024-11-10 15:45 UTC, dancergraham approved these changes

2024-11-10 15:57 UTC, merged