Add Class-Based View Mixins
django-waffle/django-waffle pull request #92
Opened 2013-10-10 22:06 UTC by ekohl

Based on @nikdoof in https://github.com/jsocol/django-waffle/issues/70#issuecomment-15744190.

2013-10-10 22:07 UTC, ekohl commented
This is a work in progress (tests are still limited), but I'd appreciate any feedback to see if this is the right path.

2013-10-28 21:50 UTC, jsocol commented
@ekohl Do you have more work to do here or ready for me to dig into it?

2013-10-28 23:51 UTC, ekohl commented
@jsocol thanks for reminding me. I added the improvements as discussed. Haven't had time to add more tests and as a user of unittest, it does take some getting used to nose. Please review though.

2013-10-29 14:23 UTC, jsocol commented on waffle/tests/test_mixin.py
> +        try:
You can use `self.assertRaises` to do this.

2013-10-29 14:24 UTC, jsocol commented on waffle/mixins.py
> +
There shouldn't be a blank line before a docstring.

2013-10-29 14:27 UTC, jsocol commented on waffle/tests/test_mixin.py
> +from nose.tools import eq_
Can you order these three imports like this?

``` python
from nose.tools import eq_
from test_utils import RequestFactory
```

Then drop the blank line between `from test_app...` and `from waffle.mid...`?

It's pedantic, I know.

2013-10-29 14:30 UTC, jsocol commented
I added some nit-picky style comments but looks good in general. With tests for the other mixins it should be ready to go.

If it helps, nose lets you use all the normal unittest assertions (`eq_` is just a shortcut for `assert a == b, '%r != %r' % (a, b)`, and `ok_`, which I rarely use, is a shortcut for `assert`), and the `TestCase` here is a subclass of the unittest `TestCase`, so it has all the methods, like `assertRaises`, available to it.

2013-10-29 14:52 UTC, ekohl commented on waffle/tests/test_mixin.py
> +from nose.tools import eq_
I love being pedantic myself, so please do.

2013-10-29 14:56 UTC, ekohl commented
@jsocol thanks. I'll update the PR with them.

2013-11-19 13:01 UTC, ekohl commented on waffle/mixins.py
> +
Not sure why autopep8 insists on this.

2013-11-19 14:46 UTC, ekohl commented
@jsocol Updated the PR.

2014-06-25 15:10 UTC, crccheck commented on waffle/mixins.py
> +        raise Http404
I'd attach a message like `raise Http404('Inactive Waffle')`. The message only shows up in debug, and can save you time trying to figure out _why_ you got a 404.

2014-06-26 07:21 UTC, ekohl commented on waffle/mixins.py
> +        raise Http404
I never did end up using waffle because of the slow response on PRs so I'm unsure if I'm going to finish this PR. This does sound like a good addition though.

2015-12-23 10:58 UTC, ekohl commented
It appears the code has been merged.

2016-04-07 19:00 UTC, nikolas commented
What commit was this code merged in? I can't find the `mixins.py` file, or `WaffleFlagMixin` when grepping the current codebase.

2016-05-17 10:56 UTC, ekohl commented
You're right, I was confused that it was merged to a fork. However, I don't have good hopes of this being merged given the activity on this PR.

2017-12-15 21:59 UTC, washeck commented
@jsocol Can this PR be re-opened? Is there anything needed to merge it?

2017-12-31 22:41 UTC, jsocol commented
I think this can probably be merged as-is but would need follow-ups with docs and any nits before being released—so I'm going to re-open for now, but not merge just yet. #269 just got merged and feels like it should probably get released ASAP so I don't necessarily want to hold up Django 2.0 compat on this new feature.

2018-01-02 20:58 UTC, ekohl commented
Rebased to fix the merge conflict and addressed comments.

2018-01-02 21:23 UTC, ekohl commented
Updated the tests to work again.

2019-02-23 17:49 UTC, clintonb requested changes
@ekohl thanks for a _lot_ of patience over so many years. Are you still interested in merging this? If so, would you mind adding some documentation so others know about these mixins?

2019-06-26 09:40 UTC, peteretep commented
hi there, we are interested in using waffle on class based views - what work remains to get this merged in?

2019-06-26 10:25 UTC, ekohl commented
@clintonb I don't have a use case for this. Because this PR was never merged I also didn't start using the library. Since I've also changed jobs and no longer work on a Django app I don't even have a potential use case. My time has become limited so I don't have time to write documentation. That said, I'd still be happy to see this merged even after all this time :)

2019-06-28 04:14 UTC, clintonb commented
@petertep this branch needs to be rebased, and we need some documentation so that others know these are available. Can you help with that?

2019-07-01 10:13 UTC, peteretep commented
will look into it yes.

2019-07-01 10:39 UTC, peteretep commented
I have rebased this work, added a page to the documentation and opened a new pull request.

2019-07-01 11:02 UTC, ekohl commented
For those who want to click: https://github.com/django-waffle/django-waffle/pull/340

2019-07-01 17:52 UTC, closed without merging